services:
  api:
    image: ghcr.io/jendib/kidmanager:latest
    pull_policy: always
    restart: always
    environment:
      KIDMANAGER_PARENT_EMAILS: '${KIDMANAGER_PARENT_EMAILS}'
      KIDMANAGER_ECOLEDIRECTE_USERNAME: '${KIDMANAGER_ECOLEDIRECTE_USERNAME}'
      KIDMANAGER_ECOLEDIRECTE_PASSWORD: '${KIDMANAGER_ECOLEDIRECTE_PASSWORD}'
      KIDMANAGER_ECOLEDIRECTE_CN: '${KIDMANAGER_ECOLEDIRECTE_CN}'
      KIDMANAGER_ECOLEDIRECTE_CV: '${KIDMANAGER_ECOLEDIRECTE_CV}'
      QUARKUS_MAILER_HOST: '${QUARKUS_MAILER_HOST}'
      QUARKUS_MAILER_USERNAME: '${QUARKUS_MAILER_USERNAME}'
      QUARKUS_MAILER_PASSWORD: '${QUARKUS_MAILER_PASSWORD}'
      QUARKUS_MAILER_FROM: '${QUARKUS_MAILER_FROM}'
    ports:
      - '10104:8080'
